### ISSUE TITLE
Ports not reachable/closed

### ISSUE THREAD

**Issue by DeerMaximum** [snsinfu/reverse-tunnel#12]
Hi @snsinfu,

I have a problem. On the server the port(60000) from the internet are not reachable. When I scan the port on the server via nmap it is open. However, from my computer it is closed. I have already tried to turn off the firewall, but it did nothing. Has this error occurred before or am I asking in the wrong place?

![netstat](https://user-images.githubusercontent.com/43999966/107254879-a50c8380-6a2f-11eb-92a5-c14fdb125914.PNG)
![nmapClient](https://user-images.githubusercontent.com/43999966/107254895-a8a00a80-6a2f-11eb-9461-61f8c7a852f9.PNG)
![nmapServer](https://user-images.githubusercontent.com/43999966/107254901-a9d13780-6a2f-11eb-80fe-18a658e753c6.PNG)
![ServerLog](https://user-images.githubusercontent.com/43999966/107254908-ab026480-6a2f-11eb-864c-2d846039797b.PNG)
![clientLog](https://user-images.githubusercontent.com/43999966/107254884-a63db080-6a2f-11eb-8321-464b114cb050.PNG)

**Comment by snsinfu** [comment]
Looks like the port is blocked by a firewall.

Is your server hosted on a cloud? If so, there may be another (external) firewall set up by the cloud provider. IIRC Amazon Lightsail has one that blocks almost all ports by default. So, make sure the required ports are open also in this kind of firewall.

**Comment by DeerMaximum** [comment]
Thanks for the tip with the firewall. It turns out that my hoster has an external firewall. Now everything works. Thanks for this great project.
