### ISSUE TITLE
Add example showing forwarding from agent to gateway server

### ISSUE THREAD

**Issue by brandonros** [snsinfu/reverse-tunnel#22]
I see the examples allow the agent to access ports from the gateway server. What about the gateway server accessing ports from the agent?

**Comment by snsinfu** [comment]
I don't fully understand the question. Do you want to access a service that is listening to localhost on the gateway server from the agent machine? So that the service does not need to be exposed to the entire internet.

(Sorry for super late reply, I was so busy on March.)

**Comment by brandonros** [comment]
https://github.com/shawwwn/Gole the example on this readme had me covered

could we make this happen with this repo?

**Comment by snsinfu** [comment]
Hmm, maybe not. Sounds like you need a point-to-point tunneling through NAT, which rtun does not cover. rtun server is a tool for exposing a locally running server to the internet.

If you want a solid solution, you should set up a site-to-site VPN through an intermediate public server [like this](https://staaldraad.github.io/2017/04/17/nat-to-nat-with-wireguard/).

Or, just set up a public ssh server (say C)  and enable port forwarding between A and B. The following commands should allow B to connect to a server running on A like the Gole example, but via a public server C.

```
# A web server is listening to localhost:8080 on A

# Set up ssh port forwardings
(machine A) $ ssh -R 9999:localhost:8080 C
(machine B) $ ssh -L 1111:localhost:9999 C

# now B can access the web server running on A
(machine B) $ curl http://localhost:1111
Hello from A
```

BTW, Gole looks interesting. Thanks for the link!

**Comment by brandonros** [comment]
SSH forwarding is very slow.
