### ISSUE TITLE
systemd service example 

### ISSUE THREAD

**Issue by 5shekel** [snsinfu/reverse-tunnel#6]
i love rtun! 
is it possible to include an example service daemon for rtun and rtun-server?

**Comment by snsinfu** [comment]
Sorry for the late reply! You have basic systemd service units in `examples/systemd` directory:

https://github.com/snsinfu/reverse-tunnel/tree/master/examples/systemd

Does it help?

**Comment by 5shekel** [comment]
Omg
Totally missed that
