### ISSUE TITLE
rtun with caddy

### ISSUE THREAD

**Issue by 5shekel** [snsinfu/reverse-tunnel#7]
trying to make this work, 
added to my Caddyfile

```
rtun.example.com {
    proxy / localhost:443 
    websocket
}
```

and followed the rtun-server readme 
changed in rtun-server.yml
```

control_address: :443

lets_encrypt:
  domain: rtun.example.com
```

**Comment by snsinfu** [comment]
Use plain HTTP (disable Let's Encrypt) on rtun-server when using Caddy. Because Caddy already does encryption.

Your Caddyfile and rtun-server.yml would look like these:

```
rtun.example.com {
    proxy / localhost:8000
    websocket
}
```

rtun-server.yml:

```
control_address: localhost:8000

agents:
  # Your rtun agents here...
```
