### ISSUE TITLE
Running on Windows

### ISSUE THREAD

**Issue by cjkini** [snsinfu/reverse-tunnel#8]
Hi guys.

Thanks for this wonderful solution. I tried it on my Linux Server and it works like a champ. :)

Anyhow, can this solution used to reverse tunnel the agent that is running on Windows?

I tried to install it in Windows, but stuck when i try to run ./rtun (in windows it is .\rtun), it will go and open the file. Not running the command to connect to the gateway server.

Thanks.

**Comment by snsinfu** [comment]
Did you download rtun from the release page? If so, it is compiled for linux or mac and does not run on Windows.

Now I uploaded [rtun.exe](https://github.com/snsinfu/reverse-tunnel/releases/download/v1.2.0/rtun.exe) to the latest release. Does this work on Windows? I don't have access to Windows environment for now, but it seems to work under wine on linux.

**Comment by cjkini** [comment]
Wow! This now works like a champ in Windows!
Thanks @snsinfu !

**Comment by cjkini** [comment]
Oh Btw, this port forwarding also can support RDP protocol as well rite?

**Comment by snsinfu** [comment]
I don't use RDP so I'm not sure, but it would work if you reverse tunnel relevant ports. Though, I don't think it's a good idea to serve RDP through a public server because RDP is really frequently targeted for attacks.

**Comment by cjkini** [comment]
Noted @snsinfu . Tq very much for your suggestion.
